Import('env')

_INCLUDES = [Dir('../include').abspath]

_SOURCES = ['TuioClient.cpp']
_SOURCES = [File('../src/' + s).abspath for s in _SOURCES]

env.Append(APP_SOURCES = _SOURCES)
env.Append(CPPPATH = _INCLUDES)

env = SConscript('../../OSC/scons/SConscript', exports = 'env')

Return('env')

