Import('env')

if env['PLATFORM'] == 'win32':
	_INCLUDES = [Dir('../include/msw').abspath]
	_LIBS = Split('CVClient.lib QTMLClient.lib QTSClient.lib QTVR.lib')
	_LIBS = [Dir('../lib/msw/x86/').abspath + '/' + s for s in _LIBS]
	env.Append(CPPPATH = _INCLUDES)
	env.Append(LIBS = _LIBS)

	_BINARIES = ['QTCF.dll']
	# TODO: use a default QT_PATH if it does not exist is env
	QT_PATH = 'c:/Program Files (x86)/QuickTime/QTSystem'
	for f in _BINARIES:
		fin = Dir(QT_PATH).abspath + '/' + f
		Command('#' + f, fin, Copy(f, fin))

Return('env')
