env = Environment()

env['APP_TARGET'] = 'Buddhabrot'
env['APP_SOURCES'] = ['Buddhabrot.cpp']
env['DEBUG'] = 0
env['PLIST'] = '../xcode/Buddhabrot-Info.plist'

SConscript('../../../scons/SConscript', exports = 'env')
