env = Environment()

env['APP_TARGET'] = 'shaderText'
env['APP_SOURCES'] = ['../shaderTest.cpp' ]
env['RESOURCES'] = ['../data/gaussianBlur_frag.glsl',
		'../data/passThru_vert.glsl', '../../data/cinder_logo.png']

SConscript('../../../scons/SConscript', exports = 'env')
