env = Environment()

env['APP_TARGET'] = 'CubeMappingApp'
env['APP_SOURCES'] = ['CubeMappingApp.cpp', 'CubeMap.cpp']
env['RESOURCES'] = ['../shaders/CubeMapping_frag.glsl', '../shaders/CubeMapping_vert.glsl', '../textures/*']

SConscript('../../../scons/SConscript', exports = 'env')
