env = Environment()

env['APP_TARGET'] = 'SurfaceBasicApp'
env['APP_SOURCES'] = ['SurfaceBasicApp.cpp']
env['RESOURCES'] = ['../../data/cinder_logo.png']

SConscript('../../../scons/SConscript', exports = 'env')
