TARGET = 'SurfaceBasicApp'
APP_SOURCES  = ['SurfaceBasicApp.cpp']
RESOURCES = ['../../data/cinder_logo.png']
DEBUG = 0

env = Environment()
env.Append(APP_SOURCES = APP_SOURCES)

SConscript('../../../scons/SConscript',
	exports = ['env', 'TARGET', 'DEBUG', 'RESOURCES'])
