env = Environment()

env['APP_TARGET'] = 'NormalMappingApp'
env['APP_SOURCES'] = ['NormalMappingApp.cpp']
env['RESOURCES'] = ['diffuseMap_3.jpg', 'normalMap_3.png',
		'specStrengthMap_3.jpg', '../shaders/normalMap.frag',
		'../shaders/normalMap.vert']

SConscript('../../../scons/SConscript', exports = 'env')
