TARGET = 'msaFluidBasicApp'
APP_SOURCES = ['msaFluidBasicApp.cpp']
DEBUG = 0

env = Environment()

# msaFluid block
env = SConscript('../../../scons/SConscript', exports = ['env'])

env.Append(APP_SOURCES = APP_SOURCES)

SConscript('../../../../../scons/SConscript',
		exports = ['env', 'TARGET', 'DEBUG'])

