TARGET = 'QuickTimeWriterApp'
APP_SOURCES  = ['QuickTimeWriterApp.cpp']
RESOURCES = ['lava.jpg']
DEBUG = 0

env = Environment()
env.Append(APP_SOURCES = APP_SOURCES)

SConscript('../../../scons/SConscript',
	exports = ['env', 'TARGET', 'DEBUG', 'RESOURCES'])
