env = Environment()

env['APP_TARGET'] = 'RDiffusionApp'
env['APP_SOURCES'] = ['RDiffusionApp.cpp']
env['RESOURCES'] = ['gsrd_frag.glsl', 'passThru_vert.glsl', 'starter.jpg']

SConscript('../../../scons/SConscript', exports = 'env')
