TARGET = 'BasicParticleApp'
APP_SOURCES  = ['BasicParticleApp.cpp']
DEBUG = 0

env = Environment()
env.Append(APP_SOURCES = APP_SOURCES)

SConscript('../../../scons/SConscript',
	exports = ['env', 'TARGET', 'DEBUG'])
