TARGET = 'ArcballDemoApp'
APP_SOURCES  = ['ArcballDemoApp.cpp']
DEBUG = 0

env = Environment()
env.Append(APP_SOURCES = APP_SOURCES)

SConscript('../../../scons/SConscript',
	exports = ['env', 'TARGET', 'DEBUG'])
