env = Environment()

env['APP_TARGET'] = 'MultichannelOutputApp'
env['APP_SOURCES'] = ['MultichannelOutputApp.cpp', File('../../common/AudioDrawUtils.cpp').abspath]

_INCLUDES = [Dir('../../common/').abspath]
env.Append(CPPPATH = _INCLUDES)

SConscript('../../../../scons/SConscript', exports = 'env')
