env = Environment()

env['APP_TARGET'] = 'ClothSimulationApp'
env['APP_SOURCES'] = ['ClothSimulationApp.cpp']
env['ASSETS'] = Split('render.frag render.vert update.vert')

SConscript('../../../../scons/SConscript', exports = 'env')
