TARGET = 'GLSLLightingApp'
APP_SOURCES  = ['GLSLLightingApp.cpp', 'InfoPanel.cpp']
RESOURCES = ['vert.glsl', 'frag.glsl']
DEBUG = 0

env = Environment()
env.Append(APP_SOURCES = APP_SOURCES)

SConscript('../../../scons/SConscript',
	exports = ['env', 'TARGET', 'DEBUG', 'RESOURCES'])
