TARGET = 'AudioPlaybackApp'
APP_SOURCES  = ['AudioPlaybackApp.cpp']
RESOURCES = ['booyah.wav']
DEBUG = 0

env = Environment()
env.Append(APP_SOURCES = APP_SOURCES)

SConscript('../../../scons/SConscript',
	exports = ['env', 'TARGET', 'DEBUG', 'RESOURCES'])
