env = Environment()

env['APP_TARGET'] = 'AudioPlaybackApp'
env['APP_SOURCES'] = ['AudioPlaybackApp.cpp']
env['RESOURCES'] = ['booyah.wav']
env['DEBUG'] = 0

SConscript('../../../scons/SConscript', exports = 'env')
