env = Environment()

env['APP_TARGET'] = 'DeferredShadingAdvancedApp'
env['APP_SOURCES'] = ['DeferredShadingAdvancedApp.cpp', 'Light.cpp', 'Material.cpp',
		'Model.cpp']
env['ASSETS'] = Split('ao/* bloom/* common/* deferred/* post/* ray/* pass_through.vert')

SConscript('../../../../scons/SConscript', exports = 'env')
