TARGET = 'QuaternionAccumApp'
APP_SOURCES  = ['QuaternionAccumApp.cpp']
RESOURCES = ['Plane.png', 'Stripe.png']
DEBUG = 0

env = Environment()
env.Append(APP_SOURCES = APP_SOURCES)

SConscript('../../../scons/SConscript',
	exports = ['env', 'TARGET', 'DEBUG', 'RESOURCES'])
