env = Environment()

env['APP_TARGET'] = 'CairoBasicApp'
env['APP_SOURCES'] = ['CairoBasicApp.cpp']

env = SConscript('../../../blocks/Cairo/scons/SConscript', exports = 'env')

SConscript('../../../scons/SConscript', exports = 'env')
