env = Environment()

env['APP_TARGET'] = 'OSCListenerApp'
env['APP_SOURCES'] = ['OSCListenerApp.cpp']

env = SConscript('../../../scons/SConscript', exports = 'env')

SConscript('../../../../../scons/SConscript', exports = 'env')

