env = Environment()

env['APP_TARGET'] = 'ObjLoaderApp'
env['APP_SOURCES'] = ['ObjLoaderApp.cpp']
env['ASSETS'] = ['8lbs.obj', 'shader.frag', 'shader.vert']

SConscript('../../../../scons/SConscript', exports = 'env')
