TARGET = 'OBJLoaderApp'
APP_SOURCES  = ['OBJLoaderApp.cpp']
RESOURCES = ['cube.obj', 'shader.frag', 'shader.vert', 'warpdodec.obj',
		'../../data/cinder_logo.png']
DEBUG = 0

env = Environment()
env.Append(APP_SOURCES = APP_SOURCES)

SConscript('../../../scons/SConscript',
	exports = ['env', 'TARGET', 'DEBUG', 'RESOURCES'])
