env = Environment()

env['APP_TARGET'] = 'OBJLoaderApp'
env['APP_SOURCES'] = ['OBJLoaderApp.cpp']
env['RESOURCES'] = ['cube.obj', 'shader.frag', 'shader.vert', 'warpdodec.obj',
		'../../data/cinder_logo.png']

SConscript('../../../scons/SConscript', exports = 'env')
